In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("./csv/open-meteo/weather_historical_2000_2026_top50_reducted.csv")
print(df.shape)

(11480688, 3)

In [15]:
df.head()

    City         Timestamp  Temperature
0  Paris  2000-01-01T00:00          6.0
1  Paris  2000-01-01T01:00          5.9
2  Paris  2000-01-01T02:00          5.9
3  Paris  2000-01-01T03:00          5.9
4  Paris  2000-01-01T04:00          6.1

In [19]:
df['datetime_tz'] = pd.to_datetime(df['Timestamp'], utc=True).dt.tz_convert('Europe/Paris')
df.head()

    City         Timestamp  Temperature               datetime_tz
0  Paris  2000-01-01T00:00          6.0 2000-01-01 01:00:00+01:00
1  Paris  2000-01-01T01:00          5.9 2000-01-01 02:00:00+01:00
2  Paris  2000-01-01T02:00          5.9 2000-01-01 03:00:00+01:00
3  Paris  2000-01-01T03:00          5.9 2000-01-01 04:00:00+01:00
4  Paris  2000-01-01T04:00          6.1 2000-01-01 05:00:00+01:00

In [25]:
df_groupby_temp = df.groupby('datetime_tz')['Temperature'].agg([
    'mean','min','max','median','std',
    ('q1', lambda x: x.quantile(0.25)),
    ('q3', lambda x: x.quantile(0.75))
]).reset_index()

In [26]:
df_groupby_temp.head()

                datetime_tz   mean  min   max  median       std     q1     q3
0 2000-01-01 01:00:00+01:00  5.110 -1.3  10.2    6.05  2.847932  2.775  6.650
1 2000-01-01 02:00:00+01:00  5.068 -1.7  10.1    5.95  2.887584  2.825  6.700
2 2000-01-01 03:00:00+01:00  5.066 -1.9  10.3    6.00  2.968516  2.675  6.900
3 2000-01-01 04:00:00+01:00  5.054 -2.2  10.5    6.00  3.054018  2.800  7.125
4 2000-01-01 05:00:00+01:00  5.074 -2.6  10.8    6.10  3.049577  3.200  7.175

In [27]:
df_groupby_temp.to_csv("./csv/open-meteo/temperature-metrics-2020-2025.csv", index=False)

In [29]:
list_cities = df['City'].unique()
print(list_cities)
print(len(list_cities))

['Paris' 'Marseille' 'Lyon' 'Toulouse' 'Nice' 'Nantes' 'Montpellier'
 'Strasbourg' 'Bordeaux' 'Lille' 'Rennes' 'Toulon' 'Reims' 'Saint-Étienne'
 'Le Havre' 'Villeurbanne' 'Dijon' 'Angers' 'Grenoble' 'Nîmes'
 'Aix-en-Provence' 'Saint-Denis' 'Clermont-Ferrand' 'Le Mans' 'Brest'
 'Tours' 'Amiens' 'Annecy' 'Limoges' 'Metz' 'Perpignan'
 'Boulogne-Billancourt' 'Besançon' 'Rouen' 'Orléans' 'Montreuil' 'Caen'
 'Argenteuil' 'Mulhouse' 'Nancy' 'Tourcoing' 'Roubaix' 'Nanterre'
 'Vitry-sur-Seine' 'Asnières-sur-Seine' 'Créteil' 'Avignon' 'Colombes'
 'Poitiers' 'Aubervilliers']
50

In [30]:
df2 = df[df['City'].isin(list_cities[:25])]
df2.shape

(5740224, 4)

In [31]:
df2_groupby_temp = df2.groupby('datetime_tz')['Temperature'].agg([
    'mean','min','max','median','std',
    ('q1', lambda x: x.quantile(0.25)),
    ('q3', lambda x: x.quantile(0.75))
]).reset_index()

In [32]:
df2_groupby_temp.head()

                datetime_tz   mean  min   max  median       std   q1   q3
0 2000-01-01 01:00:00+01:00  5.036 -1.3  10.2     4.3  3.140976  2.7  8.0
1 2000-01-01 02:00:00+01:00  5.004 -1.7  10.1     4.3  3.159836  2.8  8.1
2 2000-01-01 03:00:00+01:00  4.968 -1.9  10.3     4.4  3.282240  2.6  8.3
3 2000-01-01 04:00:00+01:00  4.952 -1.9  10.5     4.5  3.317142  2.7  8.0
4 2000-01-01 05:00:00+01:00  4.940 -1.8  10.8     4.8  3.258195  3.2  7.8

In [43]:
df_rte = pd.read_csv('./csv/power_consumption_2000_2025_hourly.csv')
df_rte['start_date'] = pd.to_datetime(df_rte['start_date'], utc=True).dt.tz_convert('Europe/Paris')
df_rte['end_date'] = pd.to_datetime(df_rte['end_date'], utc=True).dt.tz_convert('Europe/Paris')

df_rte.head()

                 start_date                  end_date    value
0 2000-01-01 00:00:00+01:00 2000-01-01 01:00:00+01:00  50094.0
1 2000-01-01 01:00:00+01:00 2000-01-01 02:00:00+01:00  49971.0
2 2000-01-01 02:00:00+01:00 2000-01-01 03:00:00+01:00  48666.5
3 2000-01-01 03:00:00+01:00 2000-01-01 04:00:00+01:00  45793.0
4 2000-01-01 04:00:00+01:00 2000-01-01 05:00:00+01:00  43498.5

In [44]:
print(df_rte.shape)
print(df_rte.dtypes)

(223486, 3)
start_date    datetime64[ns, Europe/Paris]
end_date      datetime64[ns, Europe/Paris]
value                              float64
dtype: object

In [40]:
print(df_groupby_temp.shape)
print(df_groupby_temp.dtypes)

(229632, 8)
datetime_tz    datetime64[ns, Europe/Paris]
mean                                float64
min                                 float64
max                                 float64
median                              float64
std                                 float64
q1                                  float64
q3                                  float64
dtype: object

In [45]:
df_rte_temp = pd.merge(df_rte, df_groupby_temp, left_on='end_date', right_on='datetime_tz', how="left")
df_rte_temp.head()

,start_date,end_date,value,datetime_tz,mean,min,max,median,std,q1,q3
0,2000-01-01 00:00:00+01:00,2000-01-01 01:00:00+01:00,50094.0,2000-01-01 01:00:00+01:00,5.110,-1.3,10.2,6.05,2.847932,2.775,6.650
1,2000-01-01 01:00:00+01:00,2000-01-01 02:00:00+01:00,49971.0,2000-01-01 02:00:00+01:00,5.068,-1.7,10.1,5.95,2.887584,2.825,6.700
2,2000-01-01 02:00:00+01:00,2000-01-01 03:00:00+01:00,48666.5,2000-01-01 03:00:00+01:00,5.066,-1.9,10.3,6.00,2.968516,2.675,6.900
3,2000-01-01 03:00:00+01:00,2000-01-01 04:00:00+01:00,45793.0,2000-01-01 04:00:00+01:00,5.054,-2.2,10.5,6.00,3.054018,2.800,7.125
4,2000-01-01 04:00:00+01:00,2000-01-01 05:00:00+01:00,43498.5,2000-01-01 05:00:00+01:00,5.074,-2.6,10.8,6.10,3.049577,3.200,7.175

In [ ]:
df_rte_temp.drop(columns=['datetime_tz'], inplace=True)

In [47]:
df_rte_temp.head()

,start_date,end_date,value,mean,min,max,median,std,q1,q3
0,2000-01-01 00:00:00+01:00,2000-01-01 01:00:00+01:00,50094.0,5.110,-1.3,10.2,6.05,2.847932,2.775,6.650
1,2000-01-01 01:00:00+01:00,2000-01-01 02:00:00+01:00,49971.0,5.068,-1.7,10.1,5.95,2.887584,2.825,6.700
2,2000-01-01 02:00:00+01:00,2000-01-01 03:00:00+01:00,48666.5,5.066,-1.9,10.3,6.00,2.968516,2.675,6.900
3,2000-01-01 03:00:00+01:00,2000-01-01 04:00:00+01:00,45793.0,5.054,-2.2,10.5,6.00,3.054018,2.800,7.125
4,2000-01-01 04:00:00+01:00,2000-01-01 05:00:00+01:00,43498.5,5.074,-2.6,10.8,6.10,3.049577,3.200,7.175

In [48]:
df_rte_temp.to_csv("./csv/power_consumption_meteo_2000_2025_hourly.csv", index=False)