In [1]:
import pandas as pd

In [21]:
df_final = pd.read_csv('./csv/2010_power_consumption.csv')
df_final.head()

FileNotFoundError: [Errno 2] No such file or directory: './csv/2010_power_consumption.csv'

In [15]:
# agregation by hour
df_final['start_hour'] = df_final['start_date'].str.replace(':30:', ':00:')
df_final['start_date'] = pd.to_datetime(df_final['start_date'], utc=True).dt.tz_convert('Europe/Paris')
df_final['end_date'] = pd.to_datetime(df_final['end_date'], utc=True).dt.tz_convert('Europe/Paris')
df_final['start_hour'] = pd.to_datetime(df_final['start_hour'], utc=True).dt.tz_convert('Europe/Paris')
#df_final['hour_start'] = df_final['start_date'].dt.floor('h')
#df_final['hour_end'] = df_final['hour_start'] + pd.Timedelta(hours=1)

In [18]:
df_final['end_hour'] = df_final['start_hour'] + pd.Timedelta(hours=1)
df_final.head()

,start_date,end_date,value,status,start_hour,end_hour
0,2010-01-01 00:00:00+01:00,2010-01-01 00:30:00+01:00,61437,FINAL,2010-01-01 00:00:00+01:00,2010-01-01 01:00:00+01:00
1,2010-01-01 00:30:00+01:00,2010-01-01 01:00:00+01:00,59663,FINAL,2010-01-01 00:00:00+01:00,2010-01-01 01:00:00+01:00
2,2010-01-01 01:00:00+01:00,2010-01-01 01:30:00+01:00,59839,FINAL,2010-01-01 01:00:00+01:00,2010-01-01 02:00:00+01:00
3,2010-01-01 01:30:00+01:00,2010-01-01 02:00:00+01:00,59634,FINAL,2010-01-01 01:00:00+01:00,2010-01-01 02:00:00+01:00
4,2010-01-01 02:00:00+01:00,2010-01-01 02:30:00+01:00,59361,FINAL,2010-01-01 02:00:00+01:00,2010-01-01 03:00:00+01:00

In [19]:
resampled = df_final.groupby('start_hour').agg({
    'value': 'mean',
    'start_date': 'first',
    'end_date': 'last'
}).reset_index(drop=True)

In [20]:
resampled.head(10)

     value                start_date                  end_date
0  60550.0 2010-01-01 00:00:00+01:00 2010-01-01 01:00:00+01:00
1  59736.5 2010-01-01 01:00:00+01:00 2010-01-01 02:00:00+01:00
2  58381.0 2010-01-01 02:00:00+01:00 2010-01-01 03:00:00+01:00
3  54945.5 2010-01-01 03:00:00+01:00 2010-01-01 04:00:00+01:00
4  52685.0 2010-01-01 04:00:00+01:00 2010-01-01 05:00:00+01:00
5  52142.5 2010-01-01 05:00:00+01:00 2010-01-01 06:00:00+01:00
6  52081.5 2010-01-01 06:00:00+01:00 2010-01-01 07:00:00+01:00
7  52331.5 2010-01-01 07:00:00+01:00 2010-01-01 08:00:00+01:00
8  52171.0 2010-01-01 08:00:00+01:00 2010-01-01 09:00:00+01:00
9  53463.5 2010-01-01 09:00:00+01:00 2010-01-01 10:00:00+01:00