In [2]:
import pandas as pd

In [3]:
df1_meteo = pd.read_csv('./csv/open-meteo/openmeteo_paris_2000-2009.csv')
df2_meteo = pd.read_csv('./csv/open-meteo/openmeteo_paris_2010-2025.csv')
df_meteo = pd.concat([df1_meteo, df2_meteo])
df_meteo.reset_index(inplace=True, drop=True)
df_meteo['datetime'] = pd.to_datetime(df_meteo['time'])
df_meteo.head(10)

               time  temperature_2m            datetime
0  2000-01-01T00:00             6.0 2000-01-01 00:00:00
1  2000-01-01T01:00             5.9 2000-01-01 01:00:00
2  2000-01-01T02:00             6.0 2000-01-01 02:00:00
3  2000-01-01T03:00             6.1 2000-01-01 03:00:00
4  2000-01-01T04:00             6.4 2000-01-01 04:00:00
5  2000-01-01T05:00             6.7 2000-01-01 05:00:00
6  2000-01-01T06:00             7.0 2000-01-01 06:00:00
7  2000-01-01T07:00             7.2 2000-01-01 07:00:00
8  2000-01-01T08:00             7.5 2000-01-01 08:00:00
9  2000-01-01T09:00             7.9 2000-01-01 09:00:00

In [5]:
df_meteo[ df_meteo['datetime'].dt.year == 2019 ].head()

                    time  temperature_2m            datetime
166560  2019-01-01T00:00             6.1 2019-01-01 00:00:00
166561  2019-01-01T01:00             6.4 2019-01-01 01:00:00
166562  2019-01-01T02:00             6.2 2019-01-01 02:00:00
166563  2019-01-01T03:00             6.1 2019-01-01 03:00:00
166564  2019-01-01T04:00             6.4 2019-01-01 04:00:00

In [6]:
df_rte = pd.read_csv('./csv/power_consumption_2000_2025_hourly.csv')
df_rte['start_date'] = pd.to_datetime(df_rte['start_date'], utc=True).dt.tz_convert('Europe/Paris')
df_rte['end_date'] = pd.to_datetime(df_rte['end_date'], utc=True).dt.tz_convert('Europe/Paris')
df_rte.head()

                 start_date                  end_date    value
0 2000-01-01 00:00:00+01:00 2000-01-01 01:00:00+01:00  50094.0
1 2000-01-01 01:00:00+01:00 2000-01-01 02:00:00+01:00  49971.0
2 2000-01-01 02:00:00+01:00 2000-01-01 03:00:00+01:00  48666.5
3 2000-01-01 03:00:00+01:00 2000-01-01 04:00:00+01:00  45793.0
4 2000-01-01 04:00:00+01:00 2000-01-01 05:00:00+01:00  43498.5

In [7]:
df_rte['temperature'] = 0

In [8]:
df_rte.loc[(df_rte['start_date'].dt.year >= 2000) & (df_rte['start_date'].dt.year <= 2019), 'temperature'] = df_meteo[(df_meteo['datetime'].dt.year >= 2000) & (df_meteo['datetime'].dt.year <= 2019)]['temperature_2m']
df_rte.head()

/tmp/ipykernel_33136/3906960496.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 6.   5.9  6.  ... -1.4 -1.6 -1.6]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_rte.loc[(df_rte['start_date'].dt.year >= 2000) & (df_rte['start_date'].dt.year <= 2019), 'temperature'] = df_meteo[(df_meteo['datetime'].dt.year >= 2000) & (df_meteo['datetime'].dt.year <= 2019)]['temperature_2m']

                 start_date                  end_date    value  temperature
0 2000-01-01 00:00:00+01:00 2000-01-01 01:00:00+01:00  50094.0          6.0
1 2000-01-01 01:00:00+01:00 2000-01-01 02:00:00+01:00  49971.0          5.9
2 2000-01-01 02:00:00+01:00 2000-01-01 03:00:00+01:00  48666.5          6.0
3 2000-01-01 03:00:00+01:00 2000-01-01 04:00:00+01:00  45793.0          6.1
4 2000-01-01 04:00:00+01:00 2000-01-01 05:00:00+01:00  43498.5          6.4

In [9]:
df_rte.to_csv('./csv/rte_paris.csv', index=False)